using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._VDS.Barrier.Pulveris.UI;

[GenerateTypedNameReferences]
public sealed partial class PulverisBarrierControllerWindow : FancyWindow
{
    public Action? OnToggleButtonPressed;

    public PulverisBarrierControllerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ToggleButton.OnPressed += _ => OnToggleButtonPressed?.Invoke();

    }

}
